
USE KODILLA_COURSE;

CREATE TABLE STATS(
                      STAT_ID INT(11) AUTO_INCREMENT,
                      STAT_DATE DATETIME NOT NULL,
                      STAT VARCHAR(20) NOT NULL,
                      VALUE INT(11) NOT NULL,
                      PRIMARY KEY(STAT_ID)
);

CREATE VIEW BESTSELLERS_COUNT as
SELECT COUNT(*) as BESTSELLER_COUNT FROM
    BOOKS b
where b.bestseller = 1;

SET @RENTSQTY = 0;

CREATE EVENT UPDATE_BESTSELLERS
    ON SCHEDULE EVERY 1 MINUTE
    DO
CALL UpdateBestSellers();
select * from BESTSELLERS_COUNT into @BS_COUNT;
INSERT INTO STATS (STAT_DATE, STAT, VALUE)
VALUES(curtime(), 'BESTSELLERS', @BS_COUNT);
